This is my working Skeleton of the Current project
RoboticsClubatUCF/Pac-Man pull request #1
Opened 2021-10-27 02:51 UTC by BiggiePete

This is the new addition of the Inventory page, a working Admin page, and some basic additions to get everything working,

NOTE : Search functionality is currently case sensitive, and non predictive, and also completely un-intuitive, so that is the next major improvement to be made

2021-10-29 16:49 UTC, xar-tol requested changes
Looks like a good skeleton, but can you remove the BIN files? AKA  "pacman/admin/__pycache__/...", "pacman/inventory/__pycache__/...", etc

2021-10-29 16:49 UTC, xar-tol commented on pacman/pacman/urls.py
> +    #path('admin/', include('admin.urls')),
Maybe get rid of this comment since it's not used anymore?

2021-10-29 16:49 UTC, xar-tol commented on pacman/staticfiles/css/inventory.css
> +@import url(https://raw.github.com/FortAwesome/Font-Awesome/master/docs/assets/css/font-awesome.min.css);
Good font package!

2021-10-29 16:49 UTC, xar-tol commented on pacman/staticfiles/css/inventory.css
> +table,th, td {
Can we make the spacing consistent here?

2021-10-29 16:49 UTC, xar-tol commented on pacman/staticfiles/html/inventory.html
> +	<h1 class="title">Inventory @ Robot-club</h1>
I assume this is a placeholder, but "Robot-club" should probably be "Robotics Club"

2021-10-29 16:49 UTC, xar-tol commented on pacman/inventory/models.py
> +    description = models.CharField(max_length=256)
Maybe we can add image here at some point and have it be a string that's either a link or file location?

2021-10-29 19:00 UTC, BiggiePete commented on pacman/pacman/urls.py
> +    #path('admin/', include('admin.urls')),
For your admin page to work that line would need to be uncommented, as I have it commented to skip by the admin app, and use Django's built-in page for it, not entirely sure why it worked, it just did

2021-10-29 19:00 UTC, BiggiePete commented
ill get to removing the caches on monday

2021-11-04 18:32 UTC, xar-tol commented
Replaced with #2

2021-11-04 18:32 UTC, closed without merging